/*
 * OPC UA REST API
 *
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BrowseDescription
    /// </summary>
    [DataContract(Name = "BrowseDescription")]
    public partial class BrowseDescription : IEquatable<BrowseDescription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrowseDescription" /> class.
        /// </summary>
        /// <param name="nodeId">nodeId.</param>
        /// <param name="browseDirection">browseDirection.</param>
        /// <param name="referenceTypeId">referenceTypeId.</param>
        /// <param name="includeSubtypes">includeSubtypes.</param>
        /// <param name="nodeClassMask">nodeClassMask.</param>
        /// <param name="resultMask">resultMask.</param>
        public BrowseDescription(string nodeId = default(string), int? browseDirection = null, string referenceTypeId = default(string), bool? includeSubtypes = null, int? nodeClassMask = null, int? resultMask = null)
        {
            this.NodeId = nodeId;
            this.BrowseDirection = browseDirection;
            this.ReferenceTypeId = referenceTypeId;
            this.IncludeSubtypes = includeSubtypes;
            this.NodeClassMask = nodeClassMask;
            this.ResultMask = resultMask;
        }

        /// <summary>
        /// Gets or Sets NodeId
        /// </summary>
        [DataMember(Name = "NodeId", EmitDefaultValue = false)]
        public string NodeId { get; set; }

        /// <summary>
        /// Gets or Sets BrowseDirection
        /// </summary>
        [DataMember(Name = "BrowseDirection", EmitDefaultValue = false)]
        public int? BrowseDirection { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceTypeId
        /// </summary>
        [DataMember(Name = "ReferenceTypeId", EmitDefaultValue = false)]
        public string ReferenceTypeId { get; set; }

        /// <summary>
        /// Gets or Sets IncludeSubtypes
        /// </summary>
        [DataMember(Name = "IncludeSubtypes", EmitDefaultValue = true)]
        public bool? IncludeSubtypes { get; set; }

        /// <summary>
        /// Gets or Sets NodeClassMask
        /// </summary>
        [DataMember(Name = "NodeClassMask", EmitDefaultValue = false)]
        public int? NodeClassMask { get; set; }

        /// <summary>
        /// Gets or Sets ResultMask
        /// </summary>
        [DataMember(Name = "ResultMask", EmitDefaultValue = false)]
        public int? ResultMask { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BrowseDescription {\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  BrowseDirection: ").Append(BrowseDirection).Append("\n");
            sb.Append("  ReferenceTypeId: ").Append(ReferenceTypeId).Append("\n");
            sb.Append("  IncludeSubtypes: ").Append(IncludeSubtypes).Append("\n");
            sb.Append("  NodeClassMask: ").Append(NodeClassMask).Append("\n");
            sb.Append("  ResultMask: ").Append(ResultMask).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BrowseDescription);
        }

        /// <summary>
        /// Returns true if BrowseDescription instances are equal
        /// </summary>
        /// <param name="input">Instance of BrowseDescription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BrowseDescription input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.NodeId == input.NodeId ||
                    (this.NodeId != null &&
                    this.NodeId.Equals(input.NodeId))
                ) && 
                (
                    this.BrowseDirection == input.BrowseDirection ||
                    this.BrowseDirection.Equals(input.BrowseDirection)
                ) && 
                (
                    this.ReferenceTypeId == input.ReferenceTypeId ||
                    (this.ReferenceTypeId != null &&
                    this.ReferenceTypeId.Equals(input.ReferenceTypeId))
                ) && 
                (
                    this.IncludeSubtypes == input.IncludeSubtypes ||
                    this.IncludeSubtypes.Equals(input.IncludeSubtypes)
                ) && 
                (
                    this.NodeClassMask == input.NodeClassMask ||
                    this.NodeClassMask.Equals(input.NodeClassMask)
                ) && 
                (
                    this.ResultMask == input.ResultMask ||
                    this.ResultMask.Equals(input.ResultMask)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NodeId != null)
                {
                    hashCode = (hashCode * 59) + this.NodeId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.BrowseDirection.GetHashCode();
                if (this.ReferenceTypeId != null)
                {
                    hashCode = (hashCode * 59) + this.ReferenceTypeId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IncludeSubtypes.GetHashCode();
                hashCode = (hashCode * 59) + this.NodeClassMask.GetHashCode();
                hashCode = (hashCode * 59) + this.ResultMask.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
