/*
 * OPC UA REST API
 *
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ReadRequest
    /// </summary>
    [DataContract(Name = "ReadRequest")]
    public partial class ReadRequest : IEquatable<ReadRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReadRequest" /> class.
        /// </summary>
        /// <param name="requestHeader">requestHeader.</param>
        /// <param name="maxAge">maxAge.</param>
        /// <param name="timestampsToReturn">timestampsToReturn.</param>
        /// <param name="nodesToRead">nodesToRead.</param>
        public ReadRequest(RequestHeader requestHeader = default(RequestHeader), double? maxAge = null, int? timestampsToReturn = null, List<ReadValueId> nodesToRead = default(List<ReadValueId>))
        {
            this.RequestHeader = requestHeader;
            this.MaxAge = maxAge;
            this.TimestampsToReturn = timestampsToReturn;
            this.NodesToRead = nodesToRead;
        }

        /// <summary>
        /// Gets or Sets RequestHeader
        /// </summary>
        [DataMember(Name = "RequestHeader", EmitDefaultValue = false)]
        public RequestHeader RequestHeader { get; set; }

        /// <summary>
        /// Gets or Sets MaxAge
        /// </summary>
        [DataMember(Name = "MaxAge", EmitDefaultValue = false)]
        public double? MaxAge { get; set; }

        /// <summary>
        /// Gets or Sets TimestampsToReturn
        /// </summary>
        [DataMember(Name = "TimestampsToReturn", EmitDefaultValue = false)]
        public int? TimestampsToReturn { get; set; }

        /// <summary>
        /// Gets or Sets NodesToRead
        /// </summary>
        [DataMember(Name = "NodesToRead", EmitDefaultValue = false)]
        public List<ReadValueId> NodesToRead { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReadRequest {\n");
            sb.Append("  RequestHeader: ").Append(RequestHeader).Append("\n");
            sb.Append("  MaxAge: ").Append(MaxAge).Append("\n");
            sb.Append("  TimestampsToReturn: ").Append(TimestampsToReturn).Append("\n");
            sb.Append("  NodesToRead: ").Append(NodesToRead).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReadRequest);
        }

        /// <summary>
        /// Returns true if ReadRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ReadRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReadRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RequestHeader == input.RequestHeader ||
                    (this.RequestHeader != null &&
                    this.RequestHeader.Equals(input.RequestHeader))
                ) && 
                (
                    this.MaxAge == input.MaxAge ||
                    this.MaxAge.Equals(input.MaxAge)
                ) && 
                (
                    this.TimestampsToReturn == input.TimestampsToReturn ||
                    this.TimestampsToReturn.Equals(input.TimestampsToReturn)
                ) && 
                (
                    this.NodesToRead == input.NodesToRead ||
                    this.NodesToRead != null &&
                    input.NodesToRead != null &&
                    this.NodesToRead.SequenceEqual(input.NodesToRead)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RequestHeader != null)
                {
                    hashCode = (hashCode * 59) + this.RequestHeader.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.MaxAge.GetHashCode();
                hashCode = (hashCode * 59) + this.TimestampsToReturn.GetHashCode();
                if (this.NodesToRead != null)
                {
                    hashCode = (hashCode * 59) + this.NodesToRead.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
