/*
 * OPC UA REST API
 *
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ReferenceDescription
    /// </summary>
    [DataContract(Name = "ReferenceDescription")]
    public partial class ReferenceDescription : IEquatable<ReferenceDescription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReferenceDescription" /> class.
        /// </summary>
        /// <param name="referenceTypeId">referenceTypeId.</param>
        /// <param name="isForward">isForward.</param>
        /// <param name="nodeId">nodeId.</param>
        /// <param name="browseName">browseName.</param>
        /// <param name="displayName">displayName.</param>
        /// <param name="nodeClass">nodeClass.</param>
        /// <param name="typeDefinition">typeDefinition.</param>
        public ReferenceDescription(string referenceTypeId = default(string), bool? isForward = null, string nodeId = default(string), string browseName = default(string), LocalizedText displayName = default(LocalizedText), int? nodeClass = null, string typeDefinition = default(string))
        {
            this.ReferenceTypeId = referenceTypeId;
            this.IsForward = isForward;
            this.NodeId = nodeId;
            this.BrowseName = browseName;
            this.DisplayName = displayName;
            this.NodeClass = nodeClass;
            this.TypeDefinition = typeDefinition;
        }

        /// <summary>
        /// Gets or Sets ReferenceTypeId
        /// </summary>
        [DataMember(Name = "ReferenceTypeId", EmitDefaultValue = false)]
        public string ReferenceTypeId { get; set; }

        /// <summary>
        /// Gets or Sets IsForward
        /// </summary>
        [DataMember(Name = "IsForward", EmitDefaultValue = true)]
        public bool? IsForward { get; set; }

        /// <summary>
        /// Gets or Sets NodeId
        /// </summary>
        [DataMember(Name = "NodeId", EmitDefaultValue = false)]
        public string NodeId { get; set; }

        /// <summary>
        /// Gets or Sets BrowseName
        /// </summary>
        [DataMember(Name = "BrowseName", EmitDefaultValue = false)]
        public string BrowseName { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "DisplayName", EmitDefaultValue = false)]
        public LocalizedText DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets NodeClass
        /// </summary>
        [DataMember(Name = "NodeClass", EmitDefaultValue = false)]
        public int? NodeClass { get; set; }

        /// <summary>
        /// Gets or Sets TypeDefinition
        /// </summary>
        [DataMember(Name = "TypeDefinition", EmitDefaultValue = false)]
        public string TypeDefinition { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReferenceDescription {\n");
            sb.Append("  ReferenceTypeId: ").Append(ReferenceTypeId).Append("\n");
            sb.Append("  IsForward: ").Append(IsForward).Append("\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  BrowseName: ").Append(BrowseName).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  NodeClass: ").Append(NodeClass).Append("\n");
            sb.Append("  TypeDefinition: ").Append(TypeDefinition).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReferenceDescription);
        }

        /// <summary>
        /// Returns true if ReferenceDescription instances are equal
        /// </summary>
        /// <param name="input">Instance of ReferenceDescription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReferenceDescription input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ReferenceTypeId == input.ReferenceTypeId ||
                    (this.ReferenceTypeId != null &&
                    this.ReferenceTypeId.Equals(input.ReferenceTypeId))
                ) && 
                (
                    this.IsForward == input.IsForward ||
                    this.IsForward.Equals(input.IsForward)
                ) && 
                (
                    this.NodeId == input.NodeId ||
                    (this.NodeId != null &&
                    this.NodeId.Equals(input.NodeId))
                ) && 
                (
                    this.BrowseName == input.BrowseName ||
                    (this.BrowseName != null &&
                    this.BrowseName.Equals(input.BrowseName))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.NodeClass == input.NodeClass ||
                    this.NodeClass.Equals(input.NodeClass)
                ) && 
                (
                    this.TypeDefinition == input.TypeDefinition ||
                    (this.TypeDefinition != null &&
                    this.TypeDefinition.Equals(input.TypeDefinition))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReferenceTypeId != null)
                {
                    hashCode = (hashCode * 59) + this.ReferenceTypeId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsForward.GetHashCode();
                if (this.NodeId != null)
                {
                    hashCode = (hashCode * 59) + this.NodeId.GetHashCode();
                }
                if (this.BrowseName != null)
                {
                    hashCode = (hashCode * 59) + this.BrowseName.GetHashCode();
                }
                if (this.DisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.DisplayName.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.NodeClass.GetHashCode();
                if (this.TypeDefinition != null)
                {
                    hashCode = (hashCode * 59) + this.TypeDefinition.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
