/*
 * OPC UA REST API
 *
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Reflection;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// VariantBody
    /// </summary>
    [JsonConverter(typeof(VariantBodyJsonConverter))]
    [DataContract(Name = "VariantBody")]
    public partial class VariantBody : AbstractOpenAPISchema, IEquatable<VariantBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VariantBody" /> class
        /// with the <see cref="VariantUnion" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of VariantUnion.</param>
        public VariantBody(VariantUnion actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VariantBody" /> class
        /// with the <see cref="List{VariantUnion}" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of List&lt;VariantUnion&gt;.</param>
        public VariantBody(List<VariantUnion> actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(List<VariantUnion>))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(VariantUnion))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: List<VariantUnion>, VariantUnion");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `VariantUnion`. If the actual instance is not `VariantUnion`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of VariantUnion</returns>
        public VariantUnion GetVariantUnion()
        {
            return (VariantUnion)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `List&lt;VariantUnion&gt;`. If the actual instance is not `List&lt;VariantUnion&gt;`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of List&lt;VariantUnion&gt;</returns>
        public List<VariantUnion> GetList()
        {
            return (List<VariantUnion>)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VariantBody {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, VariantBody.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of VariantBody
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of VariantBody</returns>
        public static VariantBody FromJson(string jsonString)
        {
            VariantBody newVariantBody = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newVariantBody;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(List<VariantUnion>).GetProperty("AdditionalProperties") == null)
                {
                    newVariantBody = new VariantBody(JsonConvert.DeserializeObject<List<VariantUnion>>(jsonString, VariantBody.SerializerSettings));
                }
                else
                {
                    newVariantBody = new VariantBody(JsonConvert.DeserializeObject<List<VariantUnion>>(jsonString, VariantBody.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("List<VariantUnion>");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into List<VariantUnion>: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(VariantUnion).GetProperty("AdditionalProperties") == null)
                {
                    newVariantBody = new VariantBody(JsonConvert.DeserializeObject<VariantUnion>(jsonString, VariantBody.SerializerSettings));
                }
                else
                {
                    newVariantBody = new VariantBody(JsonConvert.DeserializeObject<VariantUnion>(jsonString, VariantBody.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("VariantUnion");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into VariantUnion: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newVariantBody;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VariantBody);
        }

        /// <summary>
        /// Returns true if VariantBody instances are equal
        /// </summary>
        /// <param name="input">Instance of VariantBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VariantBody input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for VariantBody
    /// </summary>
    public class VariantBodyJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(VariantBody).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return VariantBody.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
