/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActivateSessionRequest } from './ActivateSessionRequest';
import {
    ActivateSessionRequestFromJSON,
    ActivateSessionRequestFromJSONTyped,
    ActivateSessionRequestToJSON,
} from './ActivateSessionRequest';

/**
 * 
 * @export
 * @interface ActivateSessionRequestMessage
 */
export interface ActivateSessionRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof ActivateSessionRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ActivateSessionRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ActivateSessionRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {ActivateSessionRequest}
     * @memberof ActivateSessionRequestMessage
     */
    Body?: ActivateSessionRequest;
}

/**
 * Check if a given object implements the ActivateSessionRequestMessage interface.
 */
export function instanceOfActivateSessionRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActivateSessionRequestMessageFromJSON(json: any): ActivateSessionRequestMessage {
    return ActivateSessionRequestMessageFromJSONTyped(json, false);
}

export function ActivateSessionRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivateSessionRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'Body': !exists(json, 'Body') ? undefined : ActivateSessionRequestFromJSON(json['Body']),
    };
}

export function ActivateSessionRequestMessageToJSON(value?: ActivateSessionRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'Body': ActivateSessionRequestToJSON(value.Body),
    };
}

