/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActivateSessionResponse } from './ActivateSessionResponse';
import {
    ActivateSessionResponseFromJSON,
    ActivateSessionResponseFromJSONTyped,
    ActivateSessionResponseToJSON,
} from './ActivateSessionResponse';

/**
 * 
 * @export
 * @interface ActivateSessionResponseMessage
 */
export interface ActivateSessionResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof ActivateSessionResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ActivateSessionResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ActivateSessionResponseMessage
     */
    ServiceId?: ActivateSessionResponseMessageServiceIdEnum;
    /**
     * 
     * @type {ActivateSessionResponse}
     * @memberof ActivateSessionResponseMessage
     */
    Body?: ActivateSessionResponse;
}


/**
 * @export
 */
export const ActivateSessionResponseMessageServiceIdEnum = {
    NUMBER_468: 468
} as const;
export type ActivateSessionResponseMessageServiceIdEnum = typeof ActivateSessionResponseMessageServiceIdEnum[keyof typeof ActivateSessionResponseMessageServiceIdEnum];


/**
 * Check if a given object implements the ActivateSessionResponseMessage interface.
 */
export function instanceOfActivateSessionResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActivateSessionResponseMessageFromJSON(json: any): ActivateSessionResponseMessage {
    return ActivateSessionResponseMessageFromJSONTyped(json, false);
}

export function ActivateSessionResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivateSessionResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : ActivateSessionResponseFromJSON(json['Body']),
    };
}

export function ActivateSessionResponseMessageToJSON(value?: ActivateSessionResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': ActivateSessionResponseToJSON(value.Body),
    };
}

