/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RelativePath } from './RelativePath';
import {
    RelativePathFromJSON,
    RelativePathFromJSONTyped,
    RelativePathToJSON,
} from './RelativePath';

/**
 * 
 * @export
 * @interface AttributeOperand
 */
export interface AttributeOperand {
    /**
     * 
     * @type {string}
     * @memberof AttributeOperand
     */
    NodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeOperand
     */
    Alias?: string;
    /**
     * 
     * @type {RelativePath}
     * @memberof AttributeOperand
     */
    BrowsePath?: RelativePath;
    /**
     * 
     * @type {number}
     * @memberof AttributeOperand
     */
    AttributeId?: number;
    /**
     * 
     * @type {string}
     * @memberof AttributeOperand
     */
    IndexRange?: string;
}

/**
 * Check if a given object implements the AttributeOperand interface.
 */
export function instanceOfAttributeOperand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AttributeOperandFromJSON(json: any): AttributeOperand {
    return AttributeOperandFromJSONTyped(json, false);
}

export function AttributeOperandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeOperand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NodeId': !exists(json, 'NodeId') ? undefined : json['NodeId'],
        'Alias': !exists(json, 'Alias') ? undefined : json['Alias'],
        'BrowsePath': !exists(json, 'BrowsePath') ? undefined : RelativePathFromJSON(json['BrowsePath']),
        'AttributeId': !exists(json, 'AttributeId') ? undefined : json['AttributeId'],
        'IndexRange': !exists(json, 'IndexRange') ? undefined : json['IndexRange'],
    };
}

export function AttributeOperandToJSON(value?: AttributeOperand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NodeId': value.NodeId,
        'Alias': value.Alias,
        'BrowsePath': RelativePathToJSON(value.BrowsePath),
        'AttributeId': value.AttributeId,
        'IndexRange': value.IndexRange,
    };
}

