/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BrowseRequest } from './BrowseRequest';
import {
    BrowseRequestFromJSON,
    BrowseRequestFromJSONTyped,
    BrowseRequestToJSON,
} from './BrowseRequest';

/**
 * 
 * @export
 * @interface BrowseRequestMessage
 */
export interface BrowseRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BrowseRequestMessage
     */
    ServiceId?: BrowseRequestMessageServiceIdEnum;
    /**
     * 
     * @type {BrowseRequest}
     * @memberof BrowseRequestMessage
     */
    Body: BrowseRequest;
}


/**
 * @export
 */
export const BrowseRequestMessageServiceIdEnum = {
    NUMBER_525: 525
} as const;
export type BrowseRequestMessageServiceIdEnum = typeof BrowseRequestMessageServiceIdEnum[keyof typeof BrowseRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the BrowseRequestMessage interface.
 */
export function instanceOfBrowseRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function BrowseRequestMessageFromJSON(json: any): BrowseRequestMessage {
    return BrowseRequestMessageFromJSONTyped(json, false);
}

export function BrowseRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowseRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': BrowseRequestFromJSON(json['Body']),
    };
}

export function BrowseRequestMessageToJSON(value?: BrowseRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': BrowseRequestToJSON(value.Body),
    };
}

