/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
} from './ResponseHeader';

/**
 * 
 * @export
 * @interface CancelResponse
 */
export interface CancelResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof CancelResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {number}
     * @memberof CancelResponse
     */
    CancelCount?: number;
}

/**
 * Check if a given object implements the CancelResponse interface.
 */
export function instanceOfCancelResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CancelResponseFromJSON(json: any): CancelResponse {
    return CancelResponseFromJSONTyped(json, false);
}

export function CancelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ResponseHeader': !exists(json, 'ResponseHeader') ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'CancelCount': !exists(json, 'CancelCount') ? undefined : json['CancelCount'],
    };
}

export function CancelResponseToJSON(value?: CancelResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value.ResponseHeader),
        'CancelCount': value.CancelCount,
    };
}

