/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CloseSessionResponse } from './CloseSessionResponse';
import {
    CloseSessionResponseFromJSON,
    CloseSessionResponseFromJSONTyped,
    CloseSessionResponseToJSON,
} from './CloseSessionResponse';

/**
 * 
 * @export
 * @interface CloseSessionResponseMessage
 */
export interface CloseSessionResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof CloseSessionResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CloseSessionResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CloseSessionResponseMessage
     */
    ServiceId?: CloseSessionResponseMessageServiceIdEnum;
    /**
     * 
     * @type {CloseSessionResponse}
     * @memberof CloseSessionResponseMessage
     */
    Body?: CloseSessionResponse;
}


/**
 * @export
 */
export const CloseSessionResponseMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_474: 474,
    NUMBER_395: 395
} as const;
export type CloseSessionResponseMessageServiceIdEnum = typeof CloseSessionResponseMessageServiceIdEnum[keyof typeof CloseSessionResponseMessageServiceIdEnum];


/**
 * Check if a given object implements the CloseSessionResponseMessage interface.
 */
export function instanceOfCloseSessionResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CloseSessionResponseMessageFromJSON(json: any): CloseSessionResponseMessage {
    return CloseSessionResponseMessageFromJSONTyped(json, false);
}

export function CloseSessionResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseSessionResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : CloseSessionResponseFromJSON(json['Body']),
    };
}

export function CloseSessionResponseMessageToJSON(value?: CloseSessionResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': CloseSessionResponseToJSON(value.Body),
    };
}

