/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CloseSessionRequest } from './CloseSessionRequest';
import {
    CloseSessionRequestFromJSON,
    CloseSessionRequestFromJSONTyped,
    CloseSessionRequestToJSON,
} from './CloseSessionRequest';

/**
 * 
 * @export
 * @interface CloseSessionRequestMessage
 */
export interface CloseSessionRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof CloseSessionRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CloseSessionRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CloseSessionRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CloseSessionRequestMessage
     */
    ServiceId?: CloseSessionRequestMessageServiceIdEnum;
    /**
     * 
     * @type {CloseSessionRequest}
     * @memberof CloseSessionRequestMessage
     */
    Body: CloseSessionRequest;
}


/**
 * @export
 */
export const CloseSessionRequestMessageServiceIdEnum = {
    NUMBER_471: 471
} as const;
export type CloseSessionRequestMessageServiceIdEnum = typeof CloseSessionRequestMessageServiceIdEnum[keyof typeof CloseSessionRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the CloseSessionRequestMessage interface.
 */
export function instanceOfCloseSessionRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function CloseSessionRequestMessageFromJSON(json: any): CloseSessionRequestMessage {
    return CloseSessionRequestMessageFromJSONTyped(json, false);
}

export function CloseSessionRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseSessionRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': CloseSessionRequestFromJSON(json['Body']),
    };
}

export function CloseSessionRequestMessageToJSON(value?: CloseSessionRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': CloseSessionRequestToJSON(value.Body),
    };
}

