/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateSubscriptionRequest } from './CreateSubscriptionRequest';
import {
    CreateSubscriptionRequestFromJSON,
    CreateSubscriptionRequestFromJSONTyped,
    CreateSubscriptionRequestToJSON,
} from './CreateSubscriptionRequest';

/**
 * 
 * @export
 * @interface CreateSubscriptionRequestMessage
 */
export interface CreateSubscriptionRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSubscriptionRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSubscriptionRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSubscriptionRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateSubscriptionRequestMessage
     */
    ServiceId?: CreateSubscriptionRequestMessageServiceIdEnum;
    /**
     * 
     * @type {CreateSubscriptionRequest}
     * @memberof CreateSubscriptionRequestMessage
     */
    Body: CreateSubscriptionRequest;
}


/**
 * @export
 */
export const CreateSubscriptionRequestMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_785: 785
} as const;
export type CreateSubscriptionRequestMessageServiceIdEnum = typeof CreateSubscriptionRequestMessageServiceIdEnum[keyof typeof CreateSubscriptionRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the CreateSubscriptionRequestMessage interface.
 */
export function instanceOfCreateSubscriptionRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function CreateSubscriptionRequestMessageFromJSON(json: any): CreateSubscriptionRequestMessage {
    return CreateSubscriptionRequestMessageFromJSONTyped(json, false);
}

export function CreateSubscriptionRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': CreateSubscriptionRequestFromJSON(json['Body']),
    };
}

export function CreateSubscriptionRequestMessageToJSON(value?: CreateSubscriptionRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': CreateSubscriptionRequestToJSON(value.Body),
    };
}

