/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateMonitoredItemsRequest } from './CreateMonitoredItemsRequest';
import {
    CreateMonitoredItemsRequestFromJSON,
    CreateMonitoredItemsRequestFromJSONTyped,
    CreateMonitoredItemsRequestToJSON,
} from './CreateMonitoredItemsRequest';

/**
 * 
 * @export
 * @interface CreateMonitoredItemsRequestMessage
 */
export interface CreateMonitoredItemsRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateMonitoredItemsRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateMonitoredItemsRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateMonitoredItemsRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateMonitoredItemsRequestMessage
     */
    ServiceId?: CreateMonitoredItemsRequestMessageServiceIdEnum;
    /**
     * 
     * @type {CreateMonitoredItemsRequest}
     * @memberof CreateMonitoredItemsRequestMessage
     */
    Body: CreateMonitoredItemsRequest;
}


/**
 * @export
 */
export const CreateMonitoredItemsRequestMessageServiceIdEnum = {
    NUMBER_749: 749
} as const;
export type CreateMonitoredItemsRequestMessageServiceIdEnum = typeof CreateMonitoredItemsRequestMessageServiceIdEnum[keyof typeof CreateMonitoredItemsRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the CreateMonitoredItemsRequestMessage interface.
 */
export function instanceOfCreateMonitoredItemsRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function CreateMonitoredItemsRequestMessageFromJSON(json: any): CreateMonitoredItemsRequestMessage {
    return CreateMonitoredItemsRequestMessageFromJSONTyped(json, false);
}

export function CreateMonitoredItemsRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMonitoredItemsRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': CreateMonitoredItemsRequestFromJSON(json['Body']),
    };
}

export function CreateMonitoredItemsRequestMessageToJSON(value?: CreateMonitoredItemsRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': CreateMonitoredItemsRequestToJSON(value.Body),
    };
}

