/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
} from './ResponseHeader';

/**
 * 
 * @export
 * @interface CreateSubscriptionResponse
 */
export interface CreateSubscriptionResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof CreateSubscriptionResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {number}
     * @memberof CreateSubscriptionResponse
     */
    SubscriptionId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSubscriptionResponse
     */
    RevisedPublishingInterval?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSubscriptionResponse
     */
    RevisedLifetimeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSubscriptionResponse
     */
    RevisedMaxKeepAliveCount?: number;
}

/**
 * Check if a given object implements the CreateSubscriptionResponse interface.
 */
export function instanceOfCreateSubscriptionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateSubscriptionResponseFromJSON(json: any): CreateSubscriptionResponse {
    return CreateSubscriptionResponseFromJSONTyped(json, false);
}

export function CreateSubscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ResponseHeader': !exists(json, 'ResponseHeader') ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'SubscriptionId': !exists(json, 'SubscriptionId') ? undefined : json['SubscriptionId'],
        'RevisedPublishingInterval': !exists(json, 'RevisedPublishingInterval') ? undefined : json['RevisedPublishingInterval'],
        'RevisedLifetimeCount': !exists(json, 'RevisedLifetimeCount') ? undefined : json['RevisedLifetimeCount'],
        'RevisedMaxKeepAliveCount': !exists(json, 'RevisedMaxKeepAliveCount') ? undefined : json['RevisedMaxKeepAliveCount'],
    };
}

export function CreateSubscriptionResponseToJSON(value?: CreateSubscriptionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value.ResponseHeader),
        'SubscriptionId': value.SubscriptionId,
        'RevisedPublishingInterval': value.RevisedPublishingInterval,
        'RevisedLifetimeCount': value.RevisedLifetimeCount,
        'RevisedMaxKeepAliveCount': value.RevisedMaxKeepAliveCount,
    };
}

