/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateSubscriptionResponse } from './CreateSubscriptionResponse';
import {
    CreateSubscriptionResponseFromJSON,
    CreateSubscriptionResponseFromJSONTyped,
    CreateSubscriptionResponseToJSON,
} from './CreateSubscriptionResponse';

/**
 * 
 * @export
 * @interface CreateSubscriptionResponseMessage
 */
export interface CreateSubscriptionResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSubscriptionResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSubscriptionResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateSubscriptionResponseMessage
     */
    ServiceId?: CreateSubscriptionResponseMessageServiceIdEnum;
    /**
     * 
     * @type {CreateSubscriptionResponse}
     * @memberof CreateSubscriptionResponseMessage
     */
    Body?: CreateSubscriptionResponse;
}


/**
 * @export
 */
export const CreateSubscriptionResponseMessageServiceIdEnum = {
    NUMBER_788: 788
} as const;
export type CreateSubscriptionResponseMessageServiceIdEnum = typeof CreateSubscriptionResponseMessageServiceIdEnum[keyof typeof CreateSubscriptionResponseMessageServiceIdEnum];


/**
 * Check if a given object implements the CreateSubscriptionResponseMessage interface.
 */
export function instanceOfCreateSubscriptionResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateSubscriptionResponseMessageFromJSON(json: any): CreateSubscriptionResponseMessage {
    return CreateSubscriptionResponseMessageFromJSONTyped(json, false);
}

export function CreateSubscriptionResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : CreateSubscriptionResponseFromJSON(json['Body']),
    };
}

export function CreateSubscriptionResponseMessageToJSON(value?: CreateSubscriptionResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': CreateSubscriptionResponseToJSON(value.Body),
    };
}

