/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateSessionRequest } from './CreateSessionRequest';
import {
    CreateSessionRequestFromJSON,
    CreateSessionRequestFromJSONTyped,
    CreateSessionRequestToJSON,
} from './CreateSessionRequest';

/**
 * 
 * @export
 * @interface CreateSessionRequestMessage
 */
export interface CreateSessionRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSessionRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSessionRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSessionRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateSessionRequestMessage
     */
    ServiceId?: CreateSessionRequestMessageServiceIdEnum;
    /**
     * 
     * @type {CreateSessionRequest}
     * @memberof CreateSessionRequestMessage
     */
    Body: CreateSessionRequest;
}


/**
 * @export
 */
export const CreateSessionRequestMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_459: 459
} as const;
export type CreateSessionRequestMessageServiceIdEnum = typeof CreateSessionRequestMessageServiceIdEnum[keyof typeof CreateSessionRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the CreateSessionRequestMessage interface.
 */
export function instanceOfCreateSessionRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function CreateSessionRequestMessageFromJSON(json: any): CreateSessionRequestMessage {
    return CreateSessionRequestMessageFromJSONTyped(json, false);
}

export function CreateSessionRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': CreateSessionRequestFromJSON(json['Body']),
    };
}

export function CreateSessionRequestMessageToJSON(value?: CreateSessionRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': CreateSessionRequestToJSON(value.Body),
    };
}

