/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MonitoredItemCreateRequest } from './MonitoredItemCreateRequest';
import {
    MonitoredItemCreateRequestFromJSON,
    MonitoredItemCreateRequestFromJSONTyped,
    MonitoredItemCreateRequestToJSON,
} from './MonitoredItemCreateRequest';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface CreateMonitoredItemsRequest
 */
export interface CreateMonitoredItemsRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof CreateMonitoredItemsRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {number}
     * @memberof CreateMonitoredItemsRequest
     */
    SubscriptionId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateMonitoredItemsRequest
     */
    TimestampsToReturn?: number;
    /**
     * 
     * @type {Array<MonitoredItemCreateRequest>}
     * @memberof CreateMonitoredItemsRequest
     */
    ItemsToCreate?: Array<MonitoredItemCreateRequest>;
}

/**
 * Check if a given object implements the CreateMonitoredItemsRequest interface.
 */
export function instanceOfCreateMonitoredItemsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateMonitoredItemsRequestFromJSON(json: any): CreateMonitoredItemsRequest {
    return CreateMonitoredItemsRequestFromJSONTyped(json, false);
}

export function CreateMonitoredItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMonitoredItemsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'SubscriptionId': !exists(json, 'SubscriptionId') ? undefined : json['SubscriptionId'],
        'TimestampsToReturn': !exists(json, 'TimestampsToReturn') ? undefined : json['TimestampsToReturn'],
        'ItemsToCreate': !exists(json, 'ItemsToCreate') ? undefined : ((json['ItemsToCreate'] as Array<any>).map(MonitoredItemCreateRequestFromJSON)),
    };
}

export function CreateMonitoredItemsRequestToJSON(value?: CreateMonitoredItemsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'SubscriptionId': value.SubscriptionId,
        'TimestampsToReturn': value.TimestampsToReturn,
        'ItemsToCreate': value.ItemsToCreate === undefined ? undefined : ((value.ItemsToCreate as Array<any>).map(MonitoredItemCreateRequestToJSON)),
    };
}

