/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
} from './DiagnosticInfo';
import type { MonitoredItemNotification } from './MonitoredItemNotification';
import {
    MonitoredItemNotificationFromJSON,
    MonitoredItemNotificationFromJSONTyped,
    MonitoredItemNotificationToJSON,
} from './MonitoredItemNotification';

/**
 * 
 * @export
 * @interface DataChangeNotification
 */
export interface DataChangeNotification {
    /**
     * 
     * @type {Array<MonitoredItemNotification>}
     * @memberof DataChangeNotification
     */
    MonitoredItems?: Array<MonitoredItemNotification>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof DataChangeNotification
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the DataChangeNotification interface.
 */
export function instanceOfDataChangeNotification(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DataChangeNotificationFromJSON(json: any): DataChangeNotification {
    return DataChangeNotificationFromJSONTyped(json, false);
}

export function DataChangeNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataChangeNotification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'MonitoredItems': !exists(json, 'MonitoredItems') ? undefined : ((json['MonitoredItems'] as Array<any>).map(MonitoredItemNotificationFromJSON)),
        'DiagnosticInfos': !exists(json, 'DiagnosticInfos') ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

export function DataChangeNotificationToJSON(value?: DataChangeNotification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'MonitoredItems': value.MonitoredItems === undefined ? undefined : ((value.MonitoredItems as Array<any>).map(MonitoredItemNotificationToJSON)),
        'DiagnosticInfos': value.DiagnosticInfos === undefined ? undefined : ((value.DiagnosticInfos as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

