/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataTypeDescription
 */
export interface DataTypeDescription {
    /**
     * 
     * @type {string}
     * @memberof DataTypeDescription
     */
    DataTypeId?: string;
    /**
     * 
     * @type {string}
     * @memberof DataTypeDescription
     */
    Name?: string;
}

/**
 * Check if a given object implements the DataTypeDescription interface.
 */
export function instanceOfDataTypeDescription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DataTypeDescriptionFromJSON(json: any): DataTypeDescription {
    return DataTypeDescriptionFromJSONTyped(json, false);
}

export function DataTypeDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataTypeDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'DataTypeId': !exists(json, 'DataTypeId') ? undefined : json['DataTypeId'],
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function DataTypeDescriptionToJSON(value?: DataTypeDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DataTypeId': value.DataTypeId,
        'Name': value.Name,
    };
}

