/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeleteMonitoredItemsResponse } from './DeleteMonitoredItemsResponse';
import {
    DeleteMonitoredItemsResponseFromJSON,
    DeleteMonitoredItemsResponseFromJSONTyped,
    DeleteMonitoredItemsResponseToJSON,
} from './DeleteMonitoredItemsResponse';

/**
 * 
 * @export
 * @interface DeleteMonitoredItemsResponseMessage
 */
export interface DeleteMonitoredItemsResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteMonitoredItemsResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteMonitoredItemsResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {DeleteMonitoredItemsResponse}
     * @memberof DeleteMonitoredItemsResponseMessage
     */
    Body?: DeleteMonitoredItemsResponse;
}

/**
 * Check if a given object implements the DeleteMonitoredItemsResponseMessage interface.
 */
export function instanceOfDeleteMonitoredItemsResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteMonitoredItemsResponseMessageFromJSON(json: any): DeleteMonitoredItemsResponseMessage {
    return DeleteMonitoredItemsResponseMessageFromJSONTyped(json, false);
}

export function DeleteMonitoredItemsResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMonitoredItemsResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'Body': !exists(json, 'Body') ? undefined : DeleteMonitoredItemsResponseFromJSON(json['Body']),
    };
}

export function DeleteMonitoredItemsResponseMessageToJSON(value?: DeleteMonitoredItemsResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'Body': DeleteMonitoredItemsResponseToJSON(value.Body),
    };
}

