/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface DeleteMonitoredItemsRequest
 */
export interface DeleteMonitoredItemsRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof DeleteMonitoredItemsRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {number}
     * @memberof DeleteMonitoredItemsRequest
     */
    SubscriptionId?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof DeleteMonitoredItemsRequest
     */
    MonitoredItemIds?: Array<number>;
}

/**
 * Check if a given object implements the DeleteMonitoredItemsRequest interface.
 */
export function instanceOfDeleteMonitoredItemsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteMonitoredItemsRequestFromJSON(json: any): DeleteMonitoredItemsRequest {
    return DeleteMonitoredItemsRequestFromJSONTyped(json, false);
}

export function DeleteMonitoredItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMonitoredItemsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'SubscriptionId': !exists(json, 'SubscriptionId') ? undefined : json['SubscriptionId'],
        'MonitoredItemIds': !exists(json, 'MonitoredItemIds') ? undefined : json['MonitoredItemIds'],
    };
}

export function DeleteMonitoredItemsRequestToJSON(value?: DeleteMonitoredItemsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'SubscriptionId': value.SubscriptionId,
        'MonitoredItemIds': value.MonitoredItemIds,
    };
}

