/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeleteSubscriptionsRequest } from './DeleteSubscriptionsRequest';
import {
    DeleteSubscriptionsRequestFromJSON,
    DeleteSubscriptionsRequestFromJSONTyped,
    DeleteSubscriptionsRequestToJSON,
} from './DeleteSubscriptionsRequest';

/**
 * 
 * @export
 * @interface DeleteSubscriptionsRequestMessage
 */
export interface DeleteSubscriptionsRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteSubscriptionsRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteSubscriptionsRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteSubscriptionsRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DeleteSubscriptionsRequestMessage
     */
    ServiceId?: DeleteSubscriptionsRequestMessageServiceIdEnum;
    /**
     * 
     * @type {DeleteSubscriptionsRequest}
     * @memberof DeleteSubscriptionsRequestMessage
     */
    Body: DeleteSubscriptionsRequest;
}


/**
 * @export
 */
export const DeleteSubscriptionsRequestMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_845: 845
} as const;
export type DeleteSubscriptionsRequestMessageServiceIdEnum = typeof DeleteSubscriptionsRequestMessageServiceIdEnum[keyof typeof DeleteSubscriptionsRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the DeleteSubscriptionsRequestMessage interface.
 */
export function instanceOfDeleteSubscriptionsRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function DeleteSubscriptionsRequestMessageFromJSON(json: any): DeleteSubscriptionsRequestMessage {
    return DeleteSubscriptionsRequestMessageFromJSONTyped(json, false);
}

export function DeleteSubscriptionsRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSubscriptionsRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': DeleteSubscriptionsRequestFromJSON(json['Body']),
    };
}

export function DeleteSubscriptionsRequestMessageToJSON(value?: DeleteSubscriptionsRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': DeleteSubscriptionsRequestToJSON(value.Body),
    };
}

