/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeleteMonitoredItemsRequest } from './DeleteMonitoredItemsRequest';
import {
    DeleteMonitoredItemsRequestFromJSON,
    DeleteMonitoredItemsRequestFromJSONTyped,
    DeleteMonitoredItemsRequestToJSON,
} from './DeleteMonitoredItemsRequest';

/**
 * 
 * @export
 * @interface DeleteMonitoredItemsRequestMessage
 */
export interface DeleteMonitoredItemsRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteMonitoredItemsRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteMonitoredItemsRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteMonitoredItemsRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DeleteMonitoredItemsRequestMessage
     */
    ServiceId?: DeleteMonitoredItemsRequestMessageServiceIdEnum;
    /**
     * 
     * @type {DeleteMonitoredItemsRequest}
     * @memberof DeleteMonitoredItemsRequestMessage
     */
    Body: DeleteMonitoredItemsRequest;
}


/**
 * @export
 */
export const DeleteMonitoredItemsRequestMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_779: 779
} as const;
export type DeleteMonitoredItemsRequestMessageServiceIdEnum = typeof DeleteMonitoredItemsRequestMessageServiceIdEnum[keyof typeof DeleteMonitoredItemsRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the DeleteMonitoredItemsRequestMessage interface.
 */
export function instanceOfDeleteMonitoredItemsRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function DeleteMonitoredItemsRequestMessageFromJSON(json: any): DeleteMonitoredItemsRequestMessage {
    return DeleteMonitoredItemsRequestMessageFromJSONTyped(json, false);
}

export function DeleteMonitoredItemsRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMonitoredItemsRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': DeleteMonitoredItemsRequestFromJSON(json['Body']),
    };
}

export function DeleteMonitoredItemsRequestMessageToJSON(value?: DeleteMonitoredItemsRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': DeleteMonitoredItemsRequestToJSON(value.Body),
    };
}

