/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElementOperand
 */
export interface ElementOperand {
    /**
     * 
     * @type {number}
     * @memberof ElementOperand
     */
    _Index?: number;
}

/**
 * Check if a given object implements the ElementOperand interface.
 */
export function instanceOfElementOperand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ElementOperandFromJSON(json: any): ElementOperand {
    return ElementOperandFromJSONTyped(json, false);
}

export function ElementOperandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElementOperand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_Index': !exists(json, 'Index') ? undefined : json['Index'],
    };
}

export function ElementOperandToJSON(value?: ElementOperand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Index': value._Index,
    };
}

