/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EventFieldList } from './EventFieldList';
import {
    EventFieldListFromJSON,
    EventFieldListFromJSONTyped,
    EventFieldListToJSON,
} from './EventFieldList';

/**
 * 
 * @export
 * @interface EventNotificationList
 */
export interface EventNotificationList {
    /**
     * 
     * @type {Array<EventFieldList>}
     * @memberof EventNotificationList
     */
    Events?: Array<EventFieldList>;
}

/**
 * Check if a given object implements the EventNotificationList interface.
 */
export function instanceOfEventNotificationList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventNotificationListFromJSON(json: any): EventNotificationList {
    return EventNotificationListFromJSONTyped(json, false);
}

export function EventNotificationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventNotificationList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Events': !exists(json, 'Events') ? undefined : ((json['Events'] as Array<any>).map(EventFieldListFromJSON)),
    };
}

export function EventNotificationListToJSON(value?: EventNotificationList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Events': value.Events === undefined ? undefined : ((value.Events as Array<any>).map(EventFieldListToJSON)),
    };
}

