/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Variant } from './Variant';
import {
    VariantFromJSON,
    VariantFromJSONTyped,
    VariantToJSON,
} from './Variant';

/**
 * 
 * @export
 * @interface EventFieldList
 */
export interface EventFieldList {
    /**
     * 
     * @type {number}
     * @memberof EventFieldList
     */
    ClientHandle?: number;
    /**
     * 
     * @type {Array<Variant>}
     * @memberof EventFieldList
     */
    EventFields?: Array<Variant>;
}

/**
 * Check if a given object implements the EventFieldList interface.
 */
export function instanceOfEventFieldList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventFieldListFromJSON(json: any): EventFieldList {
    return EventFieldListFromJSONTyped(json, false);
}

export function EventFieldListFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventFieldList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ClientHandle': !exists(json, 'ClientHandle') ? undefined : json['ClientHandle'],
        'EventFields': !exists(json, 'EventFields') ? undefined : ((json['EventFields'] as Array<any>).map(VariantFromJSON)),
    };
}

export function EventFieldListToJSON(value?: EventFieldList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ClientHandle': value.ClientHandle,
        'EventFields': value.EventFields === undefined ? undefined : ((value.EventFields as Array<any>).map(VariantToJSON)),
    };
}

