/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentFilterResult } from './ContentFilterResult';
import {
    ContentFilterResultFromJSON,
    ContentFilterResultFromJSONTyped,
    ContentFilterResultToJSON,
} from './ContentFilterResult';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
} from './DiagnosticInfo';

/**
 * 
 * @export
 * @interface EventFilterResult
 */
export interface EventFilterResult {
    /**
     * 
     * @type {Array<number>}
     * @memberof EventFilterResult
     */
    SelectClauseResults?: Array<number>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof EventFilterResult
     */
    SelectClauseDiagnosticInfos?: Array<DiagnosticInfo>;
    /**
     * 
     * @type {ContentFilterResult}
     * @memberof EventFilterResult
     */
    WhereClauseResult?: ContentFilterResult;
}

/**
 * Check if a given object implements the EventFilterResult interface.
 */
export function instanceOfEventFilterResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventFilterResultFromJSON(json: any): EventFilterResult {
    return EventFilterResultFromJSONTyped(json, false);
}

export function EventFilterResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventFilterResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'SelectClauseResults': !exists(json, 'SelectClauseResults') ? undefined : json['SelectClauseResults'],
        'SelectClauseDiagnosticInfos': !exists(json, 'SelectClauseDiagnosticInfos') ? undefined : ((json['SelectClauseDiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
        'WhereClauseResult': !exists(json, 'WhereClauseResult') ? undefined : ContentFilterResultFromJSON(json['WhereClauseResult']),
    };
}

export function EventFilterResultToJSON(value?: EventFilterResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SelectClauseResults': value.SelectClauseResults,
        'SelectClauseDiagnosticInfos': value.SelectClauseDiagnosticInfos === undefined ? undefined : ((value.SelectClauseDiagnosticInfos as Array<any>).map(DiagnosticInfoToJSON)),
        'WhereClauseResult': ContentFilterResultToJSON(value.WhereClauseResult),
    };
}

