/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface FindServersRequest
 */
export interface FindServersRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof FindServersRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {string}
     * @memberof FindServersRequest
     */
    EndpointUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindServersRequest
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindServersRequest
     */
    ServerUris?: Array<string>;
}

/**
 * Check if a given object implements the FindServersRequest interface.
 */
export function instanceOfFindServersRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FindServersRequestFromJSON(json: any): FindServersRequest {
    return FindServersRequestFromJSONTyped(json, false);
}

export function FindServersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindServersRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'EndpointUrl': !exists(json, 'EndpointUrl') ? undefined : json['EndpointUrl'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
    };
}

export function FindServersRequestToJSON(value?: FindServersRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'EndpointUrl': value.EndpointUrl,
        'LocaleIds': value.LocaleIds,
        'ServerUris': value.ServerUris,
    };
}

