/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FindServersRequest } from './FindServersRequest';
import {
    FindServersRequestFromJSON,
    FindServersRequestFromJSONTyped,
    FindServersRequestToJSON,
} from './FindServersRequest';

/**
 * 
 * @export
 * @interface FindServersRequestMessage
 */
export interface FindServersRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof FindServersRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindServersRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindServersRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof FindServersRequestMessage
     */
    ServiceId?: FindServersRequestMessageServiceIdEnum;
    /**
     * 
     * @type {FindServersRequest}
     * @memberof FindServersRequestMessage
     */
    Body: FindServersRequest;
}


/**
 * @export
 */
export const FindServersRequestMessageServiceIdEnum = {
    NUMBER_420: 420
} as const;
export type FindServersRequestMessageServiceIdEnum = typeof FindServersRequestMessageServiceIdEnum[keyof typeof FindServersRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the FindServersRequestMessage interface.
 */
export function instanceOfFindServersRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function FindServersRequestMessageFromJSON(json: any): FindServersRequestMessage {
    return FindServersRequestMessageFromJSONTyped(json, false);
}

export function FindServersRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindServersRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': FindServersRequestFromJSON(json['Body']),
    };
}

export function FindServersRequestMessageToJSON(value?: FindServersRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': FindServersRequestToJSON(value.Body),
    };
}

