/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetEndpointsRequest } from './GetEndpointsRequest';
import {
    GetEndpointsRequestFromJSON,
    GetEndpointsRequestFromJSONTyped,
    GetEndpointsRequestToJSON,
} from './GetEndpointsRequest';

/**
 * 
 * @export
 * @interface GetEndpointsRequestMessage
 */
export interface GetEndpointsRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetEndpointsRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetEndpointsRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetEndpointsRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {GetEndpointsRequest}
     * @memberof GetEndpointsRequestMessage
     */
    Body?: GetEndpointsRequest;
}

/**
 * Check if a given object implements the GetEndpointsRequestMessage interface.
 */
export function instanceOfGetEndpointsRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetEndpointsRequestMessageFromJSON(json: any): GetEndpointsRequestMessage {
    return GetEndpointsRequestMessageFromJSONTyped(json, false);
}

export function GetEndpointsRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEndpointsRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'Body': !exists(json, 'Body') ? undefined : GetEndpointsRequestFromJSON(json['Body']),
    };
}

export function GetEndpointsRequestMessageToJSON(value?: GetEndpointsRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'Body': GetEndpointsRequestToJSON(value.Body),
    };
}

