/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Variant } from './Variant';
import {
    VariantFromJSON,
    VariantFromJSONTyped,
    VariantToJSON,
} from './Variant';

/**
 * 
 * @export
 * @interface HistoryEventFieldList
 */
export interface HistoryEventFieldList {
    /**
     * 
     * @type {Array<Variant>}
     * @memberof HistoryEventFieldList
     */
    EventFields?: Array<Variant>;
}

/**
 * Check if a given object implements the HistoryEventFieldList interface.
 */
export function instanceOfHistoryEventFieldList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryEventFieldListFromJSON(json: any): HistoryEventFieldList {
    return HistoryEventFieldListFromJSONTyped(json, false);
}

export function HistoryEventFieldListFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryEventFieldList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'EventFields': !exists(json, 'EventFields') ? undefined : ((json['EventFields'] as Array<any>).map(VariantFromJSON)),
    };
}

export function HistoryEventFieldListToJSON(value?: HistoryEventFieldList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'EventFields': value.EventFields === undefined ? undefined : ((value.EventFields as Array<any>).map(VariantToJSON)),
    };
}

