/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HistoryReadRequest } from './HistoryReadRequest';
import {
    HistoryReadRequestFromJSON,
    HistoryReadRequestFromJSONTyped,
    HistoryReadRequestToJSON,
} from './HistoryReadRequest';

/**
 * 
 * @export
 * @interface HistoryReadRequestMessage
 */
export interface HistoryReadRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof HistoryReadRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof HistoryReadRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof HistoryReadRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof HistoryReadRequestMessage
     */
    ServiceId?: HistoryReadRequestMessageServiceIdEnum;
    /**
     * 
     * @type {HistoryReadRequest}
     * @memberof HistoryReadRequestMessage
     */
    Body: HistoryReadRequest;
}


/**
 * @export
 */
export const HistoryReadRequestMessageServiceIdEnum = {
    NUMBER_662: 662
} as const;
export type HistoryReadRequestMessageServiceIdEnum = typeof HistoryReadRequestMessageServiceIdEnum[keyof typeof HistoryReadRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the HistoryReadRequestMessage interface.
 */
export function instanceOfHistoryReadRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function HistoryReadRequestMessageFromJSON(json: any): HistoryReadRequestMessage {
    return HistoryReadRequestMessageFromJSONTyped(json, false);
}

export function HistoryReadRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryReadRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': HistoryReadRequestFromJSON(json['Body']),
    };
}

export function HistoryReadRequestMessageToJSON(value?: HistoryReadRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': HistoryReadRequestToJSON(value.Body),
    };
}

