/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Variant } from './Variant';
import {
    VariantFromJSON,
    VariantFromJSONTyped,
    VariantToJSON,
} from './Variant';

/**
 * 
 * @export
 * @interface KeyValuePair
 */
export interface KeyValuePair {
    /**
     * 
     * @type {string}
     * @memberof KeyValuePair
     */
    Key?: string;
    /**
     * 
     * @type {Variant}
     * @memberof KeyValuePair
     */
    Value?: Variant;
}

/**
 * Check if a given object implements the KeyValuePair interface.
 */
export function instanceOfKeyValuePair(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function KeyValuePairFromJSON(json: any): KeyValuePair {
    return KeyValuePairFromJSONTyped(json, false);
}

export function KeyValuePairFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyValuePair {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Key': !exists(json, 'Key') ? undefined : json['Key'],
        'Value': !exists(json, 'Value') ? undefined : VariantFromJSON(json['Value']),
    };
}

export function KeyValuePairToJSON(value?: KeyValuePair | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Key': value.Key,
        'Value': VariantToJSON(value.Value),
    };
}

