/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface ModifySubscriptionRequest
 */
export interface ModifySubscriptionRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof ModifySubscriptionRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionRequest
     */
    SubscriptionId?: number;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionRequest
     */
    RequestedPublishingInterval?: number;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionRequest
     */
    RequestedLifetimeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionRequest
     */
    RequestedMaxKeepAliveCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionRequest
     */
    MaxNotificationsPerPublish?: number;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionRequest
     */
    Priority?: number;
}

/**
 * Check if a given object implements the ModifySubscriptionRequest interface.
 */
export function instanceOfModifySubscriptionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModifySubscriptionRequestFromJSON(json: any): ModifySubscriptionRequest {
    return ModifySubscriptionRequestFromJSONTyped(json, false);
}

export function ModifySubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifySubscriptionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'SubscriptionId': !exists(json, 'SubscriptionId') ? undefined : json['SubscriptionId'],
        'RequestedPublishingInterval': !exists(json, 'RequestedPublishingInterval') ? undefined : json['RequestedPublishingInterval'],
        'RequestedLifetimeCount': !exists(json, 'RequestedLifetimeCount') ? undefined : json['RequestedLifetimeCount'],
        'RequestedMaxKeepAliveCount': !exists(json, 'RequestedMaxKeepAliveCount') ? undefined : json['RequestedMaxKeepAliveCount'],
        'MaxNotificationsPerPublish': !exists(json, 'MaxNotificationsPerPublish') ? undefined : json['MaxNotificationsPerPublish'],
        'Priority': !exists(json, 'Priority') ? undefined : json['Priority'],
    };
}

export function ModifySubscriptionRequestToJSON(value?: ModifySubscriptionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'SubscriptionId': value.SubscriptionId,
        'RequestedPublishingInterval': value.RequestedPublishingInterval,
        'RequestedLifetimeCount': value.RequestedLifetimeCount,
        'RequestedMaxKeepAliveCount': value.RequestedMaxKeepAliveCount,
        'MaxNotificationsPerPublish': value.MaxNotificationsPerPublish,
        'Priority': value.Priority,
    };
}

