/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModifySubscriptionRequest } from './ModifySubscriptionRequest';
import {
    ModifySubscriptionRequestFromJSON,
    ModifySubscriptionRequestFromJSONTyped,
    ModifySubscriptionRequestToJSON,
} from './ModifySubscriptionRequest';

/**
 * 
 * @export
 * @interface ModifySubscriptionRequestMessage
 */
export interface ModifySubscriptionRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof ModifySubscriptionRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModifySubscriptionRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModifySubscriptionRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionRequestMessage
     */
    ServiceId?: ModifySubscriptionRequestMessageServiceIdEnum;
    /**
     * 
     * @type {ModifySubscriptionRequest}
     * @memberof ModifySubscriptionRequestMessage
     */
    Body: ModifySubscriptionRequest;
}


/**
 * @export
 */
export const ModifySubscriptionRequestMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_791: 791
} as const;
export type ModifySubscriptionRequestMessageServiceIdEnum = typeof ModifySubscriptionRequestMessageServiceIdEnum[keyof typeof ModifySubscriptionRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the ModifySubscriptionRequestMessage interface.
 */
export function instanceOfModifySubscriptionRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function ModifySubscriptionRequestMessageFromJSON(json: any): ModifySubscriptionRequestMessage {
    return ModifySubscriptionRequestMessageFromJSONTyped(json, false);
}

export function ModifySubscriptionRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifySubscriptionRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': ModifySubscriptionRequestFromJSON(json['Body']),
    };
}

export function ModifySubscriptionRequestMessageToJSON(value?: ModifySubscriptionRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': ModifySubscriptionRequestToJSON(value.Body),
    };
}

