/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModifyMonitoredItemsRequest } from './ModifyMonitoredItemsRequest';
import {
    ModifyMonitoredItemsRequestFromJSON,
    ModifyMonitoredItemsRequestFromJSONTyped,
    ModifyMonitoredItemsRequestToJSON,
} from './ModifyMonitoredItemsRequest';

/**
 * 
 * @export
 * @interface ModifyMonitoredItemsRequestMessage
 */
export interface ModifyMonitoredItemsRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof ModifyMonitoredItemsRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModifyMonitoredItemsRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModifyMonitoredItemsRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {ModifyMonitoredItemsRequest}
     * @memberof ModifyMonitoredItemsRequestMessage
     */
    Body?: ModifyMonitoredItemsRequest;
}

/**
 * Check if a given object implements the ModifyMonitoredItemsRequestMessage interface.
 */
export function instanceOfModifyMonitoredItemsRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModifyMonitoredItemsRequestMessageFromJSON(json: any): ModifyMonitoredItemsRequestMessage {
    return ModifyMonitoredItemsRequestMessageFromJSONTyped(json, false);
}

export function ModifyMonitoredItemsRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyMonitoredItemsRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'Body': !exists(json, 'Body') ? undefined : ModifyMonitoredItemsRequestFromJSON(json['Body']),
    };
}

export function ModifyMonitoredItemsRequestMessageToJSON(value?: ModifyMonitoredItemsRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'Body': ModifyMonitoredItemsRequestToJSON(value.Body),
    };
}

