/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataValue } from './DataValue';
import {
    DataValueFromJSON,
    DataValueFromJSONTyped,
    DataValueToJSON,
} from './DataValue';

/**
 * 
 * @export
 * @interface MonitoredItemNotification
 */
export interface MonitoredItemNotification {
    /**
     * 
     * @type {number}
     * @memberof MonitoredItemNotification
     */
    ClientHandle?: number;
    /**
     * 
     * @type {DataValue}
     * @memberof MonitoredItemNotification
     */
    Value?: DataValue;
}

/**
 * Check if a given object implements the MonitoredItemNotification interface.
 */
export function instanceOfMonitoredItemNotification(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MonitoredItemNotificationFromJSON(json: any): MonitoredItemNotification {
    return MonitoredItemNotificationFromJSONTyped(json, false);
}

export function MonitoredItemNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoredItemNotification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ClientHandle': !exists(json, 'ClientHandle') ? undefined : json['ClientHandle'],
        'Value': !exists(json, 'Value') ? undefined : DataValueFromJSON(json['Value']),
    };
}

export function MonitoredItemNotificationToJSON(value?: MonitoredItemNotification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ClientHandle': value.ClientHandle,
        'Value': DataValueToJSON(value.Value),
    };
}

