/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExtensionObject } from './ExtensionObject';
import {
    ExtensionObjectFromJSON,
    ExtensionObjectFromJSONTyped,
    ExtensionObjectToJSON,
} from './ExtensionObject';

/**
 * 
 * @export
 * @interface MonitoredItemCreateResult
 */
export interface MonitoredItemCreateResult {
    /**
     * 
     * @type {number}
     * @memberof MonitoredItemCreateResult
     */
    StatusCode?: number;
    /**
     * 
     * @type {number}
     * @memberof MonitoredItemCreateResult
     */
    MonitoredItemId?: number;
    /**
     * 
     * @type {number}
     * @memberof MonitoredItemCreateResult
     */
    RevisedSamplingInterval?: number;
    /**
     * 
     * @type {number}
     * @memberof MonitoredItemCreateResult
     */
    RevisedQueueSize?: number;
    /**
     * 
     * @type {ExtensionObject}
     * @memberof MonitoredItemCreateResult
     */
    FilterResult?: ExtensionObject;
}

/**
 * Check if a given object implements the MonitoredItemCreateResult interface.
 */
export function instanceOfMonitoredItemCreateResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MonitoredItemCreateResultFromJSON(json: any): MonitoredItemCreateResult {
    return MonitoredItemCreateResultFromJSONTyped(json, false);
}

export function MonitoredItemCreateResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoredItemCreateResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'StatusCode': !exists(json, 'StatusCode') ? undefined : json['StatusCode'],
        'MonitoredItemId': !exists(json, 'MonitoredItemId') ? undefined : json['MonitoredItemId'],
        'RevisedSamplingInterval': !exists(json, 'RevisedSamplingInterval') ? undefined : json['RevisedSamplingInterval'],
        'RevisedQueueSize': !exists(json, 'RevisedQueueSize') ? undefined : json['RevisedQueueSize'],
        'FilterResult': !exists(json, 'FilterResult') ? undefined : ExtensionObjectFromJSON(json['FilterResult']),
    };
}

export function MonitoredItemCreateResultToJSON(value?: MonitoredItemCreateResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'StatusCode': value.StatusCode,
        'MonitoredItemId': value.MonitoredItemId,
        'RevisedSamplingInterval': value.RevisedSamplingInterval,
        'RevisedQueueSize': value.RevisedQueueSize,
        'FilterResult': ExtensionObjectToJSON(value.FilterResult),
    };
}

