/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MonitoringMode = {
    Disabled: 0,
    Sampling: 1,
    Reporting: 2
} as const;
export type MonitoringMode = typeof MonitoringMode[keyof typeof MonitoringMode];


export function MonitoringModeFromJSON(json: any): MonitoringMode {
    return MonitoringModeFromJSONTyped(json, false);
}

export function MonitoringModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoringMode {
    return json as MonitoringMode;
}

export function MonitoringModeToJSON(value?: MonitoringMode | null): any {
    return value as any;
}

