/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MonitoringParameters } from './MonitoringParameters';
import {
    MonitoringParametersFromJSON,
    MonitoringParametersFromJSONTyped,
    MonitoringParametersToJSON,
} from './MonitoringParameters';

/**
 * 
 * @export
 * @interface MonitoredItemModifyRequest
 */
export interface MonitoredItemModifyRequest {
    /**
     * 
     * @type {number}
     * @memberof MonitoredItemModifyRequest
     */
    MonitoredItemId?: number;
    /**
     * 
     * @type {MonitoringParameters}
     * @memberof MonitoredItemModifyRequest
     */
    RequestedParameters?: MonitoringParameters;
}

/**
 * Check if a given object implements the MonitoredItemModifyRequest interface.
 */
export function instanceOfMonitoredItemModifyRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MonitoredItemModifyRequestFromJSON(json: any): MonitoredItemModifyRequest {
    return MonitoredItemModifyRequestFromJSONTyped(json, false);
}

export function MonitoredItemModifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoredItemModifyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'MonitoredItemId': !exists(json, 'MonitoredItemId') ? undefined : json['MonitoredItemId'],
        'RequestedParameters': !exists(json, 'RequestedParameters') ? undefined : MonitoringParametersFromJSON(json['RequestedParameters']),
    };
}

export function MonitoredItemModifyRequestToJSON(value?: MonitoredItemModifyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'MonitoredItemId': value.MonitoredItemId,
        'RequestedParameters': MonitoringParametersToJSON(value.RequestedParameters),
    };
}

