/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MonitoringParameters } from './MonitoringParameters';
import {
    MonitoringParametersFromJSON,
    MonitoringParametersFromJSONTyped,
    MonitoringParametersToJSON,
} from './MonitoringParameters';
import type { ReadValueId } from './ReadValueId';
import {
    ReadValueIdFromJSON,
    ReadValueIdFromJSONTyped,
    ReadValueIdToJSON,
} from './ReadValueId';

/**
 * 
 * @export
 * @interface MonitoredItemCreateRequest
 */
export interface MonitoredItemCreateRequest {
    /**
     * 
     * @type {ReadValueId}
     * @memberof MonitoredItemCreateRequest
     */
    ItemToMonitor?: ReadValueId;
    /**
     * 
     * @type {number}
     * @memberof MonitoredItemCreateRequest
     */
    MonitoringMode?: number;
    /**
     * 
     * @type {MonitoringParameters}
     * @memberof MonitoredItemCreateRequest
     */
    RequestedParameters?: MonitoringParameters;
}

/**
 * Check if a given object implements the MonitoredItemCreateRequest interface.
 */
export function instanceOfMonitoredItemCreateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MonitoredItemCreateRequestFromJSON(json: any): MonitoredItemCreateRequest {
    return MonitoredItemCreateRequestFromJSONTyped(json, false);
}

export function MonitoredItemCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoredItemCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ItemToMonitor': !exists(json, 'ItemToMonitor') ? undefined : ReadValueIdFromJSON(json['ItemToMonitor']),
        'MonitoringMode': !exists(json, 'MonitoringMode') ? undefined : json['MonitoringMode'],
        'RequestedParameters': !exists(json, 'RequestedParameters') ? undefined : MonitoringParametersFromJSON(json['RequestedParameters']),
    };
}

export function MonitoredItemCreateRequestToJSON(value?: MonitoredItemCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ItemToMonitor': ReadValueIdToJSON(value.ItemToMonitor),
        'MonitoringMode': value.MonitoringMode,
        'RequestedParameters': MonitoringParametersToJSON(value.RequestedParameters),
    };
}

