/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PublishResponse } from './PublishResponse';
import {
    PublishResponseFromJSON,
    PublishResponseFromJSONTyped,
    PublishResponseToJSON,
} from './PublishResponse';

/**
 * 
 * @export
 * @interface PublishResponseMessage
 */
export interface PublishResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof PublishResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublishResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof PublishResponseMessage
     */
    ServiceId?: PublishResponseMessageServiceIdEnum;
    /**
     * 
     * @type {PublishResponse}
     * @memberof PublishResponseMessage
     */
    Body?: PublishResponse;
}


/**
 * @export
 */
export const PublishResponseMessageServiceIdEnum = {
    NUMBER_827: 827
} as const;
export type PublishResponseMessageServiceIdEnum = typeof PublishResponseMessageServiceIdEnum[keyof typeof PublishResponseMessageServiceIdEnum];


/**
 * Check if a given object implements the PublishResponseMessage interface.
 */
export function instanceOfPublishResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublishResponseMessageFromJSON(json: any): PublishResponseMessage {
    return PublishResponseMessageFromJSONTyped(json, false);
}

export function PublishResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : PublishResponseFromJSON(json['Body']),
    };
}

export function PublishResponseMessageToJSON(value?: PublishResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': PublishResponseToJSON(value.Body),
    };
}

