/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PublishRequest } from './PublishRequest';
import {
    PublishRequestFromJSON,
    PublishRequestFromJSONTyped,
    PublishRequestToJSON,
} from './PublishRequest';

/**
 * 
 * @export
 * @interface PublishRequestMessage
 */
export interface PublishRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof PublishRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublishRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublishRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof PublishRequestMessage
     */
    ServiceId?: PublishRequestMessageServiceIdEnum;
    /**
     * 
     * @type {PublishRequest}
     * @memberof PublishRequestMessage
     */
    Body: PublishRequest;
}


/**
 * @export
 */
export const PublishRequestMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_824: 824
} as const;
export type PublishRequestMessageServiceIdEnum = typeof PublishRequestMessageServiceIdEnum[keyof typeof PublishRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the PublishRequestMessage interface.
 */
export function instanceOfPublishRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function PublishRequestMessageFromJSON(json: any): PublishRequestMessage {
    return PublishRequestMessageFromJSONTyped(json, false);
}

export function PublishRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': PublishRequestFromJSON(json['Body']),
    };
}

export function PublishRequestMessageToJSON(value?: PublishRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': PublishRequestToJSON(value.Body),
    };
}

