/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface RegisterNodesRequest
 */
export interface RegisterNodesRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof RegisterNodesRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterNodesRequest
     */
    NodesToRegister?: Array<string>;
}

/**
 * Check if a given object implements the RegisterNodesRequest interface.
 */
export function instanceOfRegisterNodesRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RegisterNodesRequestFromJSON(json: any): RegisterNodesRequest {
    return RegisterNodesRequestFromJSONTyped(json, false);
}

export function RegisterNodesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterNodesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'NodesToRegister': !exists(json, 'NodesToRegister') ? undefined : json['NodesToRegister'],
    };
}

export function RegisterNodesRequestToJSON(value?: RegisterNodesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'NodesToRegister': value.NodesToRegister,
    };
}

