/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RegisterNodesResponse } from './RegisterNodesResponse';
import {
    RegisterNodesResponseFromJSON,
    RegisterNodesResponseFromJSONTyped,
    RegisterNodesResponseToJSON,
} from './RegisterNodesResponse';

/**
 * 
 * @export
 * @interface RegisterNodesResponseMessage
 */
export interface RegisterNodesResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterNodesResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterNodesResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof RegisterNodesResponseMessage
     */
    ServiceId?: RegisterNodesResponseMessageServiceIdEnum;
    /**
     * 
     * @type {RegisterNodesResponse}
     * @memberof RegisterNodesResponseMessage
     */
    Body?: RegisterNodesResponse;
}


/**
 * @export
 */
export const RegisterNodesResponseMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_561: 561,
    NUMBER_395: 395
} as const;
export type RegisterNodesResponseMessageServiceIdEnum = typeof RegisterNodesResponseMessageServiceIdEnum[keyof typeof RegisterNodesResponseMessageServiceIdEnum];


/**
 * Check if a given object implements the RegisterNodesResponseMessage interface.
 */
export function instanceOfRegisterNodesResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RegisterNodesResponseMessageFromJSON(json: any): RegisterNodesResponseMessage {
    return RegisterNodesResponseMessageFromJSONTyped(json, false);
}

export function RegisterNodesResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterNodesResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : RegisterNodesResponseFromJSON(json['Body']),
    };
}

export function RegisterNodesResponseMessageToJSON(value?: RegisterNodesResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': RegisterNodesResponseToJSON(value.Body),
    };
}

