/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RegisterNodesRequest } from './RegisterNodesRequest';
import {
    RegisterNodesRequestFromJSON,
    RegisterNodesRequestFromJSONTyped,
    RegisterNodesRequestToJSON,
} from './RegisterNodesRequest';

/**
 * 
 * @export
 * @interface RegisterNodesRequestMessage
 */
export interface RegisterNodesRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterNodesRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterNodesRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterNodesRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof RegisterNodesRequestMessage
     */
    ServiceId?: RegisterNodesRequestMessageServiceIdEnum;
    /**
     * 
     * @type {RegisterNodesRequest}
     * @memberof RegisterNodesRequestMessage
     */
    Body: RegisterNodesRequest;
}


/**
 * @export
 */
export const RegisterNodesRequestMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_558: 558
} as const;
export type RegisterNodesRequestMessageServiceIdEnum = typeof RegisterNodesRequestMessageServiceIdEnum[keyof typeof RegisterNodesRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the RegisterNodesRequestMessage interface.
 */
export function instanceOfRegisterNodesRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function RegisterNodesRequestMessageFromJSON(json: any): RegisterNodesRequestMessage {
    return RegisterNodesRequestMessageFromJSONTyped(json, false);
}

export function RegisterNodesRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterNodesRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': RegisterNodesRequestFromJSON(json['Body']),
    };
}

export function RegisterNodesRequestMessageToJSON(value?: RegisterNodesRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': RegisterNodesRequestToJSON(value.Body),
    };
}

