/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
} from './ResponseHeader';

/**
 * 
 * @export
 * @interface RegisterNodesResponse
 */
export interface RegisterNodesResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof RegisterNodesResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterNodesResponse
     */
    RegisteredNodeIds?: Array<string>;
}

/**
 * Check if a given object implements the RegisterNodesResponse interface.
 */
export function instanceOfRegisterNodesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RegisterNodesResponseFromJSON(json: any): RegisterNodesResponse {
    return RegisterNodesResponseFromJSONTyped(json, false);
}

export function RegisterNodesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterNodesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ResponseHeader': !exists(json, 'ResponseHeader') ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'RegisteredNodeIds': !exists(json, 'RegisteredNodeIds') ? undefined : json['RegisteredNodeIds'],
    };
}

export function RegisterNodesResponseToJSON(value?: RegisterNodesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value.ResponseHeader),
        'RegisteredNodeIds': value.RegisteredNodeIds,
    };
}

