/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RepublishResponse } from './RepublishResponse';
import {
    RepublishResponseFromJSON,
    RepublishResponseFromJSONTyped,
    RepublishResponseToJSON,
} from './RepublishResponse';

/**
 * 
 * @export
 * @interface RepublishResponseMessage
 */
export interface RepublishResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof RepublishResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RepublishResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof RepublishResponseMessage
     */
    ServiceId?: RepublishResponseMessageServiceIdEnum;
    /**
     * 
     * @type {RepublishResponse}
     * @memberof RepublishResponseMessage
     */
    Body?: RepublishResponse;
}


/**
 * @export
 */
export const RepublishResponseMessageServiceIdEnum = {
    NUMBER_833: 833
} as const;
export type RepublishResponseMessageServiceIdEnum = typeof RepublishResponseMessageServiceIdEnum[keyof typeof RepublishResponseMessageServiceIdEnum];


/**
 * Check if a given object implements the RepublishResponseMessage interface.
 */
export function instanceOfRepublishResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RepublishResponseMessageFromJSON(json: any): RepublishResponseMessage {
    return RepublishResponseMessageFromJSONTyped(json, false);
}

export function RepublishResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepublishResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : RepublishResponseFromJSON(json['Body']),
    };
}

export function RepublishResponseMessageToJSON(value?: RepublishResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': RepublishResponseToJSON(value.Body),
    };
}

