/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RepublishRequest } from './RepublishRequest';
import {
    RepublishRequestFromJSON,
    RepublishRequestFromJSONTyped,
    RepublishRequestToJSON,
} from './RepublishRequest';

/**
 * 
 * @export
 * @interface RepublishRequestMessage
 */
export interface RepublishRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof RepublishRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RepublishRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RepublishRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {RepublishRequest}
     * @memberof RepublishRequestMessage
     */
    Body?: RepublishRequest;
}

/**
 * Check if a given object implements the RepublishRequestMessage interface.
 */
export function instanceOfRepublishRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RepublishRequestMessageFromJSON(json: any): RepublishRequestMessage {
    return RepublishRequestMessageFromJSONTyped(json, false);
}

export function RepublishRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepublishRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'Body': !exists(json, 'Body') ? undefined : RepublishRequestFromJSON(json['Body']),
    };
}

export function RepublishRequestMessageToJSON(value?: RepublishRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'Body': RepublishRequestToJSON(value.Body),
    };
}

