/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface SetMonitoringModeRequest
 */
export interface SetMonitoringModeRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof SetMonitoringModeRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {number}
     * @memberof SetMonitoringModeRequest
     */
    SubscriptionId?: number;
    /**
     * 
     * @type {number}
     * @memberof SetMonitoringModeRequest
     */
    MonitoringMode?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof SetMonitoringModeRequest
     */
    MonitoredItemIds?: Array<number>;
}

/**
 * Check if a given object implements the SetMonitoringModeRequest interface.
 */
export function instanceOfSetMonitoringModeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SetMonitoringModeRequestFromJSON(json: any): SetMonitoringModeRequest {
    return SetMonitoringModeRequestFromJSONTyped(json, false);
}

export function SetMonitoringModeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetMonitoringModeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'SubscriptionId': !exists(json, 'SubscriptionId') ? undefined : json['SubscriptionId'],
        'MonitoringMode': !exists(json, 'MonitoringMode') ? undefined : json['MonitoringMode'],
        'MonitoredItemIds': !exists(json, 'MonitoredItemIds') ? undefined : json['MonitoredItemIds'],
    };
}

export function SetMonitoringModeRequestToJSON(value?: SetMonitoringModeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'SubscriptionId': value.SubscriptionId,
        'MonitoringMode': value.MonitoringMode,
        'MonitoredItemIds': value.MonitoredItemIds,
    };
}

