/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface SetPublishingModeRequest
 */
export interface SetPublishingModeRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof SetPublishingModeRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {boolean}
     * @memberof SetPublishingModeRequest
     */
    PublishingEnabled?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof SetPublishingModeRequest
     */
    SubscriptionIds?: Array<number>;
}

/**
 * Check if a given object implements the SetPublishingModeRequest interface.
 */
export function instanceOfSetPublishingModeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SetPublishingModeRequestFromJSON(json: any): SetPublishingModeRequest {
    return SetPublishingModeRequestFromJSONTyped(json, false);
}

export function SetPublishingModeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPublishingModeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'PublishingEnabled': !exists(json, 'PublishingEnabled') ? undefined : json['PublishingEnabled'],
        'SubscriptionIds': !exists(json, 'SubscriptionIds') ? undefined : json['SubscriptionIds'],
    };
}

export function SetPublishingModeRequestToJSON(value?: SetPublishingModeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'PublishingEnabled': value.PublishingEnabled,
        'SubscriptionIds': value.SubscriptionIds,
    };
}

