/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SetPublishingModeResponse } from './SetPublishingModeResponse';
import {
    SetPublishingModeResponseFromJSON,
    SetPublishingModeResponseFromJSONTyped,
    SetPublishingModeResponseToJSON,
} from './SetPublishingModeResponse';

/**
 * 
 * @export
 * @interface SetPublishingModeResponseMessage
 */
export interface SetPublishingModeResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof SetPublishingModeResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SetPublishingModeResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SetPublishingModeResponseMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {SetPublishingModeResponse}
     * @memberof SetPublishingModeResponseMessage
     */
    Body?: SetPublishingModeResponse;
}

/**
 * Check if a given object implements the SetPublishingModeResponseMessage interface.
 */
export function instanceOfSetPublishingModeResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SetPublishingModeResponseMessageFromJSON(json: any): SetPublishingModeResponseMessage {
    return SetPublishingModeResponseMessageFromJSONTyped(json, false);
}

export function SetPublishingModeResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPublishingModeResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : SetPublishingModeResponseFromJSON(json['Body']),
    };
}

export function SetPublishingModeResponseMessageToJSON(value?: SetPublishingModeResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': SetPublishingModeResponseToJSON(value.Body),
    };
}

