/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SetTriggeringRequest } from './SetTriggeringRequest';
import {
    SetTriggeringRequestFromJSON,
    SetTriggeringRequestFromJSONTyped,
    SetTriggeringRequestToJSON,
} from './SetTriggeringRequest';

/**
 * 
 * @export
 * @interface SetTriggeringRequestMessage
 */
export interface SetTriggeringRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof SetTriggeringRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SetTriggeringRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SetTriggeringRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SetTriggeringRequestMessage
     */
    ServiceId?: SetTriggeringRequestMessageServiceIdEnum;
    /**
     * 
     * @type {SetTriggeringRequest}
     * @memberof SetTriggeringRequestMessage
     */
    Body: SetTriggeringRequest;
}


/**
 * @export
 */
export const SetTriggeringRequestMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_773: 773
} as const;
export type SetTriggeringRequestMessageServiceIdEnum = typeof SetTriggeringRequestMessageServiceIdEnum[keyof typeof SetTriggeringRequestMessageServiceIdEnum];


/**
 * Check if a given object implements the SetTriggeringRequestMessage interface.
 */
export function instanceOfSetTriggeringRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "Body" in value;

    return isInstance;
}

export function SetTriggeringRequestMessageFromJSON(json: any): SetTriggeringRequestMessage {
    return SetTriggeringRequestMessageFromJSONTyped(json, false);
}

export function SetTriggeringRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetTriggeringRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': SetTriggeringRequestFromJSON(json['Body']),
    };
}

export function SetTriggeringRequestMessageToJSON(value?: SetTriggeringRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': SetTriggeringRequestToJSON(value.Body),
    };
}

