/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignedSoftwareCertificate
 */
export interface SignedSoftwareCertificate {
    /**
     * 
     * @type {string}
     * @memberof SignedSoftwareCertificate
     */
    CertificateData?: string;
    /**
     * 
     * @type {string}
     * @memberof SignedSoftwareCertificate
     */
    Signature?: string;
}

/**
 * Check if a given object implements the SignedSoftwareCertificate interface.
 */
export function instanceOfSignedSoftwareCertificate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SignedSoftwareCertificateFromJSON(json: any): SignedSoftwareCertificate {
    return SignedSoftwareCertificateFromJSONTyped(json, false);
}

export function SignedSoftwareCertificateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignedSoftwareCertificate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CertificateData': !exists(json, 'CertificateData') ? undefined : json['CertificateData'],
        'Signature': !exists(json, 'Signature') ? undefined : json['Signature'],
    };
}

export function SignedSoftwareCertificateToJSON(value?: SignedSoftwareCertificate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CertificateData': value.CertificateData,
        'Signature': value.Signature,
    };
}

