/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
} from './DiagnosticInfo';

/**
 * 
 * @export
 * @interface StatusChangeNotification
 */
export interface StatusChangeNotification {
    /**
     * 
     * @type {number}
     * @memberof StatusChangeNotification
     */
    Status?: number;
    /**
     * 
     * @type {DiagnosticInfo}
     * @memberof StatusChangeNotification
     */
    DiagnosticInfo?: DiagnosticInfo;
}

/**
 * Check if a given object implements the StatusChangeNotification interface.
 */
export function instanceOfStatusChangeNotification(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StatusChangeNotificationFromJSON(json: any): StatusChangeNotification {
    return StatusChangeNotificationFromJSONTyped(json, false);
}

export function StatusChangeNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusChangeNotification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Status': !exists(json, 'Status') ? undefined : json['Status'],
        'DiagnosticInfo': !exists(json, 'DiagnosticInfo') ? undefined : DiagnosticInfoFromJSON(json['DiagnosticInfo']),
    };
}

export function StatusChangeNotificationToJSON(value?: StatusChangeNotification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Status': value.Status,
        'DiagnosticInfo': DiagnosticInfoToJSON(value.DiagnosticInfo),
    };
}

