/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StructureDefinition } from './StructureDefinition';
import {
    StructureDefinitionFromJSON,
    StructureDefinitionFromJSONTyped,
    StructureDefinitionToJSON,
} from './StructureDefinition';

/**
 * 
 * @export
 * @interface StructureDescription
 */
export interface StructureDescription {
    /**
     * 
     * @type {StructureDefinition}
     * @memberof StructureDescription
     */
    StructureDefinition?: StructureDefinition;
    /**
     * 
     * @type {string}
     * @memberof StructureDescription
     */
    DataTypeId?: string;
    /**
     * 
     * @type {string}
     * @memberof StructureDescription
     */
    Name?: string;
}

/**
 * Check if a given object implements the StructureDescription interface.
 */
export function instanceOfStructureDescription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StructureDescriptionFromJSON(json: any): StructureDescription {
    return StructureDescriptionFromJSONTyped(json, false);
}

export function StructureDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructureDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'StructureDefinition': !exists(json, 'StructureDefinition') ? undefined : StructureDefinitionFromJSON(json['StructureDefinition']),
        'DataTypeId': !exists(json, 'DataTypeId') ? undefined : json['DataTypeId'],
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function StructureDescriptionToJSON(value?: StructureDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'StructureDefinition': StructureDefinitionToJSON(value.StructureDefinition),
        'DataTypeId': value.DataTypeId,
        'Name': value.Name,
    };
}

