/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TransferSubscriptionsResponse } from './TransferSubscriptionsResponse';
import {
    TransferSubscriptionsResponseFromJSON,
    TransferSubscriptionsResponseFromJSONTyped,
    TransferSubscriptionsResponseToJSON,
} from './TransferSubscriptionsResponse';

/**
 * 
 * @export
 * @interface TransferSubscriptionsResponseMessage
 */
export interface TransferSubscriptionsResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof TransferSubscriptionsResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransferSubscriptionsResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TransferSubscriptionsResponseMessage
     */
    ServiceId?: TransferSubscriptionsResponseMessageServiceIdEnum;
    /**
     * 
     * @type {TransferSubscriptionsResponse}
     * @memberof TransferSubscriptionsResponseMessage
     */
    Body?: TransferSubscriptionsResponse;
}


/**
 * @export
 */
export const TransferSubscriptionsResponseMessageServiceIdEnum = {
    NUMBER_0: 0,
    NUMBER_842: 842,
    NUMBER_395: 395
} as const;
export type TransferSubscriptionsResponseMessageServiceIdEnum = typeof TransferSubscriptionsResponseMessageServiceIdEnum[keyof typeof TransferSubscriptionsResponseMessageServiceIdEnum];


/**
 * Check if a given object implements the TransferSubscriptionsResponseMessage interface.
 */
export function instanceOfTransferSubscriptionsResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransferSubscriptionsResponseMessageFromJSON(json: any): TransferSubscriptionsResponseMessage {
    return TransferSubscriptionsResponseMessageFromJSONTyped(json, false);
}

export function TransferSubscriptionsResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferSubscriptionsResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : TransferSubscriptionsResponseFromJSON(json['Body']),
    };
}

export function TransferSubscriptionsResponseMessageToJSON(value?: TransferSubscriptionsResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': TransferSubscriptionsResponseToJSON(value.Body),
    };
}

