/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TransferSubscriptionsRequest } from './TransferSubscriptionsRequest';
import {
    TransferSubscriptionsRequestFromJSON,
    TransferSubscriptionsRequestFromJSONTyped,
    TransferSubscriptionsRequestToJSON,
} from './TransferSubscriptionsRequest';

/**
 * 
 * @export
 * @interface TransferSubscriptionsRequestMessage
 */
export interface TransferSubscriptionsRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof TransferSubscriptionsRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransferSubscriptionsRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransferSubscriptionsRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TransferSubscriptionsRequestMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {TransferSubscriptionsRequest}
     * @memberof TransferSubscriptionsRequestMessage
     */
    Body?: TransferSubscriptionsRequest;
}

/**
 * Check if a given object implements the TransferSubscriptionsRequestMessage interface.
 */
export function instanceOfTransferSubscriptionsRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransferSubscriptionsRequestMessageFromJSON(json: any): TransferSubscriptionsRequestMessage {
    return TransferSubscriptionsRequestMessageFromJSONTyped(json, false);
}

export function TransferSubscriptionsRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferSubscriptionsRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : TransferSubscriptionsRequestFromJSON(json['Body']),
    };
}

export function TransferSubscriptionsRequestMessageToJSON(value?: TransferSubscriptionsRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': TransferSubscriptionsRequestToJSON(value.Body),
    };
}

