/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UnregisterNodesRequest } from './UnregisterNodesRequest';
import {
    UnregisterNodesRequestFromJSON,
    UnregisterNodesRequestFromJSONTyped,
    UnregisterNodesRequestToJSON,
} from './UnregisterNodesRequest';

/**
 * 
 * @export
 * @interface UnregisterNodesRequestMessage
 */
export interface UnregisterNodesRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof UnregisterNodesRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnregisterNodesRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnregisterNodesRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {UnregisterNodesRequest}
     * @memberof UnregisterNodesRequestMessage
     */
    Body?: UnregisterNodesRequest;
}

/**
 * Check if a given object implements the UnregisterNodesRequestMessage interface.
 */
export function instanceOfUnregisterNodesRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UnregisterNodesRequestMessageFromJSON(json: any): UnregisterNodesRequestMessage {
    return UnregisterNodesRequestMessageFromJSONTyped(json, false);
}

export function UnregisterNodesRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnregisterNodesRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'Body': !exists(json, 'Body') ? undefined : UnregisterNodesRequestFromJSON(json['Body']),
    };
}

export function UnregisterNodesRequestMessageToJSON(value?: UnregisterNodesRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'Body': UnregisterNodesRequestToJSON(value.Body),
    };
}

