/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UnregisterNodesResponse } from './UnregisterNodesResponse';
import {
    UnregisterNodesResponseFromJSON,
    UnregisterNodesResponseFromJSONTyped,
    UnregisterNodesResponseToJSON,
} from './UnregisterNodesResponse';

/**
 * 
 * @export
 * @interface UnregisterNodesResponseMessage
 */
export interface UnregisterNodesResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof UnregisterNodesResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnregisterNodesResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof UnregisterNodesResponseMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {UnregisterNodesResponse}
     * @memberof UnregisterNodesResponseMessage
     */
    Body?: UnregisterNodesResponse;
}

/**
 * Check if a given object implements the UnregisterNodesResponseMessage interface.
 */
export function instanceOfUnregisterNodesResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UnregisterNodesResponseMessageFromJSON(json: any): UnregisterNodesResponseMessage {
    return UnregisterNodesResponseMessageFromJSONTyped(json, false);
}

export function UnregisterNodesResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnregisterNodesResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : UnregisterNodesResponseFromJSON(json['Body']),
    };
}

export function UnregisterNodesResponseMessageToJSON(value?: UnregisterNodesResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': UnregisterNodesResponseToJSON(value.Body),
    };
}

