/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface UnregisterNodesRequest
 */
export interface UnregisterNodesRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof UnregisterNodesRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnregisterNodesRequest
     */
    NodesToUnregister?: Array<string>;
}

/**
 * Check if a given object implements the UnregisterNodesRequest interface.
 */
export function instanceOfUnregisterNodesRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UnregisterNodesRequestFromJSON(json: any): UnregisterNodesRequest {
    return UnregisterNodesRequestFromJSONTyped(json, false);
}

export function UnregisterNodesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnregisterNodesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'NodesToUnregister': !exists(json, 'NodesToUnregister') ? undefined : json['NodesToUnregister'],
    };
}

export function UnregisterNodesRequestToJSON(value?: UnregisterNodesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'NodesToUnregister': value.NodesToUnregister,
    };
}

