/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserIdentityToken
 */
export interface UserIdentityToken {
    /**
     * 
     * @type {string}
     * @memberof UserIdentityToken
     */
    PolicyId?: string;
}

/**
 * Check if a given object implements the UserIdentityToken interface.
 */
export function instanceOfUserIdentityToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserIdentityTokenFromJSON(json: any): UserIdentityToken {
    return UserIdentityTokenFromJSONTyped(json, false);
}

export function UserIdentityTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdentityToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'PolicyId': !exists(json, 'PolicyId') ? undefined : json['PolicyId'],
    };
}

export function UserIdentityTokenToJSON(value?: UserIdentityToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PolicyId': value.PolicyId,
    };
}

