/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserNameIdentityToken
 */
export interface UserNameIdentityToken {
    /**
     * 
     * @type {string}
     * @memberof UserNameIdentityToken
     */
    UserName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserNameIdentityToken
     */
    Password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserNameIdentityToken
     */
    EncryptionAlgorithm?: string;
    /**
     * 
     * @type {string}
     * @memberof UserNameIdentityToken
     */
    PolicyId?: string;
}

/**
 * Check if a given object implements the UserNameIdentityToken interface.
 */
export function instanceOfUserNameIdentityToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserNameIdentityTokenFromJSON(json: any): UserNameIdentityToken {
    return UserNameIdentityTokenFromJSONTyped(json, false);
}

export function UserNameIdentityTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserNameIdentityToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'UserName': !exists(json, 'UserName') ? undefined : json['UserName'],
        'Password': !exists(json, 'Password') ? undefined : json['Password'],
        'EncryptionAlgorithm': !exists(json, 'EncryptionAlgorithm') ? undefined : json['EncryptionAlgorithm'],
        'PolicyId': !exists(json, 'PolicyId') ? undefined : json['PolicyId'],
    };
}

export function UserNameIdentityTokenToJSON(value?: UserNameIdentityToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'UserName': value.UserName,
        'Password': value.Password,
        'EncryptionAlgorithm': value.EncryptionAlgorithm,
        'PolicyId': value.PolicyId,
    };
}

