/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface X509IdentityToken
 */
export interface X509IdentityToken {
    /**
     * 
     * @type {string}
     * @memberof X509IdentityToken
     */
    CertificateData?: string;
    /**
     * 
     * @type {string}
     * @memberof X509IdentityToken
     */
    PolicyId?: string;
}

/**
 * Check if a given object implements the X509IdentityToken interface.
 */
export function instanceOfX509IdentityToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function X509IdentityTokenFromJSON(json: any): X509IdentityToken {
    return X509IdentityTokenFromJSONTyped(json, false);
}

export function X509IdentityTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): X509IdentityToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CertificateData': !exists(json, 'CertificateData') ? undefined : json['CertificateData'],
        'PolicyId': !exists(json, 'PolicyId') ? undefined : json['PolicyId'],
    };
}

export function X509IdentityTokenToJSON(value?: X509IdentityToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CertificateData': value.CertificateData,
        'PolicyId': value.PolicyId,
    };
}

