/*
 * opcfoundation.org:2024_10:starterkit:measurements
 *
 * A placeholder API that allows OpenAPI tools to be used to generate code for a companion specification.
 *
 * The version of the OpenAPI document: 1.00.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Measurements.Client.OpenAPIDateConverter;

namespace Measurements.Model
{
    /// <summary>
    /// OrientationDataType
    /// </summary>
    [DataContract(Name = "OrientationDataType")]
    public partial class OrientationDataType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrientationDataType" /> class.
        /// </summary>
        /// <param name="profileName">profileName.</param>
        /// <param name="x">x.</param>
        /// <param name="y">y.</param>
        /// <param name="rotation">rotation.</param>
        public OrientationDataType(string profileName = default(string), double x = default(double), double y = default(double), double rotation = default(double))
        {
            this.ProfileName = profileName;
            this.X = x;
            this.Y = y;
            this.Rotation = rotation;
        }

        /// <summary>
        /// Gets or Sets ProfileName
        /// </summary>
        [DataMember(Name = "ProfileName", EmitDefaultValue = false)]
        public string ProfileName { get; set; }

        /// <summary>
        /// Gets or Sets X
        /// </summary>
        [DataMember(Name = "X", EmitDefaultValue = false)]
        public double X { get; set; }

        /// <summary>
        /// Gets or Sets Y
        /// </summary>
        [DataMember(Name = "Y", EmitDefaultValue = false)]
        public double Y { get; set; }

        /// <summary>
        /// Gets or Sets Rotation
        /// </summary>
        [DataMember(Name = "Rotation", EmitDefaultValue = false)]
        public double Rotation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrientationDataType {\n");
            sb.Append("  ProfileName: ").Append(ProfileName).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Rotation: ").Append(Rotation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
