/*
 * opcfoundation.org:2024_10:starterkit:measurements
 *
 * A placeholder API that allows OpenAPI tools to be used to generate code for a companion specification.
 *
 * The version of the OpenAPI document: 1.00.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Measurements.Model;
using Measurements.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Measurements.Test.Model
{
    /// <summary>
    ///  Class for testing Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Response
        //private Response instance;

        public ResponseTests()
        {
            // TODO uncomment below to create an instance of Response
            //instance = new Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Response
        /// </summary>
        [Fact]
        public void ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Response
            //Assert.IsType<Response>(instance);
        }

        /// <summary>
        /// Test the property 'OrientationDataType'
        /// </summary>
        [Fact]
        public void OrientationDataTypeTest()
        {
            // TODO unit test for the property 'OrientationDataType'
        }
    }
}
